### ISSUE TITLE
Persian Version

### ISSUE THREAD

**Issue by M4SooD** [hail2u/html-best-practices#103]
Hi,
Is there any Persian translation of this repo?
If not i would be glad to translate it

**Comment by hail2u** [comment]
There is no Persian translation.

**Comment by ShayanTheNerd** [comment]
> There is no Persian translation.

Hey there,
Would you like to assign it to me? I'd be more than happy to contribute to this great source of HTML best practices; it'll probably be done in a couple days.
If the answer is yes, just tell me and I'll get started.

**Comment by hail2u** [comment]
Translation is always welcome.

**Comment by hail2u** [comment]
Persian translation was added in #122.
