### ISSUE TITLE
Wrong name of paths + pluralization

### ISSUE THREAD

**Issue by Hoticus** [hail2u/html-best-practices#121]
`http://you.example.com/apple-touch-icon-precomposed.png` is an absolute path, while `/apple-touch-icon-precomposed.png` is a relative path, so it must be renamed here:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/65857100/227723750-b0ad2b68-6dae-4159-9692-9d861c756620.png">

Moreover I have added a pluralization in the title.

---

In the English translation it should be:

- Use absolute path for internal links -> Use relative paths for internal links
- An absolute path works better on your localhost without internet connection. -> A relative path works better on your localhost without internet connection.

---

In the Russian translation it should be:

- Используйте абсолютный путь для внутренних ссылок -> Используйте относительные пути для внутренних ссылок
- Абсолютный путь лучше работает на локальном хосте без подключения к Интернету. -> Относительный путь лучше работает на локальном хосте без подключения к Интернету.

**Comment by Hoticus** [comment]
So it must be also fixed in other translation

**Comment by hail2u** [comment]
https://github.com/hail2u/html-best-practices/pull/119#issuecomment-1475131415
