### ISSUE TITLE
"Don’t mix empty element format" could be "always self close empty elements"

### ISSUE THREAD

**Issue by vinilneves** [hail2u/html-best-practices#128]
"Don’t mix empty element format" could be "always self close empty elements"

Instead of 

> Bad:
> ```
> <img alt="HTML Best Practices" src="/img/logo.png">
> <hr />
> ```
> Good:
> ```
> <img alt="HTML Best Practices" src="/img/logo.png">
> <hr>
> ```

Could be

> Bad:
> ```html
> <img alt="HTML Best Practices" src="/img/logo.png">
> <hr />
> ```
>
> Good:
> ```html
> <img alt="HTML Best Practices" src="/img/logo.png" />
><hr />
> ```

PS. Also use html type for code blocks

**Comment by hail2u** [comment]
No. Just don’t mix. Omitting slash is completely valid.
