### ISSUE TITLE
Discussion: embedded SVG

### ISSUE THREAD

**Issue by momdo** [hail2u/html-best-practices#15]
Example1:

```
<img src="cat.svg" alt="pretty cat">
```

Example2:

```
<object type="image/svg+xml" data="cat.svg">
  <img src="cat.png" alt="pretty cat">
</object>
```

たぶん古いIE対応が一番面倒かと思われるSVG、思いついたものを簡単に例示だけしてみました。
よりよい方法があればベストプラクティスとして記載されてもよいのかなと。

**Comment by jonathanlinat** [comment]
Can we have an english translation in order to help to resolve this issue?

**Comment by hail2u** [comment]
Google Translate is our friend.
