### ISSUE TITLE
Omit boolean attribute value→Omit boolean attribute name

### ISSUE THREAD

**Issue by momdo** [hail2u/html-best-practices#22]
省略できるのは、属性値ではなく属性名では
参考：属性名の省略 ― SGML の短縮タグ機構 | 鳩丸よもやま話 http://bakera.jp/yomoyama/shorttag#section1-2

**Comment by hail2u** [comment]
HTML5だとその辺りがSGMLから独自の規定へと変わって、普通に書く場合は、

```html
<input disabled="disabled">
```

と属性名とまったく同じ(an ASCII case-insensitive match for the attribute's canonical name)に値を書くわけですが、

```html
<input disabled="">
```

と[空文字列(the empty string)でも書け][1]、

```html
<input disabled>
```

[属性名だけだとその値は暗黙に空文字列とみなされる][2]ので、こう属性名だけ書いても良いと理解してました。


[1]: http://www.w3.org/TR/html5/infrastructure.html#boolean-attributes
[2]: http://www.w3.org/TR/html5/syntax.html#attributes-0

**Comment by momdo** [comment]
あ、確かにHTML5だと変わってますね。
忘れてやってください……。
