### ISSUE TITLE
Wrong Closing Tag

### ISSUE THREAD

**Issue by trumball** [hail2u/html-best-practices#24]
In the Embedded content section, under "Provide fallback `img` element for `picture` element". 

<picture>
      <source srcset="/img/logo.webp" type="image/webp">
      <source srcset="/img/logo.hdp" type="image/vnd.ms-photo">
      <source srcset="/img/logo.jp2" type="image/jp2">
      <source srcset="/img/logo.jpg" type="image/jpg">
</video>

-- Should Be --

<picture>
      <source srcset="/img/logo.webp" type="image/webp">
      <source srcset="/img/logo.hdp" type="image/vnd.ms-photo">
      <source srcset="/img/logo.jp2" type="image/jp2">
      <source srcset="/img/logo.jpg" type="image/jpg">
</picture>

**Comment by hail2u** [comment]
Can’t see your comment, but fixed. Thanks!

**Comment by trumball** [comment]
Many thanks
,
Kyo, you guys are doing an awesome job, thank you so much.
