### ISSUE TITLE
Do we need `version` attribute on SVG?

### ISSUE THREAD

**Issue by momdo** [hail2u/html-best-practices#34]
名前空間は省略するのセクションで

```
<svg version="1.1">
  ...
</svg>
```

とありますが、SVG2では廃止されています。
http://www.w3.org/TR/2015/WD-SVG2-20150915/changes.html#structure

ちなみに、Advent Calendar 3日目:SVG画像を1バイトでも削るためのコードゴルフ（2013年の記事）
http://d.hatena.ne.jp/rikuo/20131203#p201312d07
によれば

>正直これは省略するかは悩むところです。現在 SVG2が策定中 なこと、また将来的にはさらにバージョンが増える可能性も否定できないため、普通に使うのであれば念の為 一応バージョンは記述しておいた方が良いかなとは個人的には考えています。
>ただ省略しても現時点ではそう問題もないので、コードゴルフなら削るのもありかなと。

とはあります。

**Comment by hail2u** [comment]
省略すべきかどうか、はSVGでどうすべきかというような話だと思うので、特には言及しない方が良さそうですね。その上でWHATWG仕様でちょくちょく出てくるSVGのコード例に合わせて`version`属性は削ってしまうのが良さそう、と考えたのでそうしておきます。
