### ISSUE TITLE
Unexpected space characters

### ISSUE THREAD

**Issue by momdo** [hail2u/html-best-practices#36]
下記のようなある長さ以上の文の場合、mdで改行するために予期しないスペースが紛れ込むようです。（絶対に改行するんだ、という意向があると却下になりそうですが。）

>これらの文字は簡単に他の文字と間違えられます。また、仕様ではこれらの文字に人間に わかりやすい名前がついているかどうかを保証していません。
>長ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーい 行はとっっっっっっっっっっっっっっっっっっっっっっっっっっっても読みづらいです。

**Comment by hail2u** [comment]
日本語では改行を入れない方が良さそうですね。忘れてました。
