### ISSUE TITLE
About prefer strong native semantics

### ISSUE THREAD

**Issue by momdo** [hail2u/html-best-practices#37]
英語版では"Prefer strong native semantics"ですが、日本語版では「暗黙のセマンティクスを尊重する」になっているので、英語を日本語版にあわせた方がよいかと思います。

あと
> わざわざ指定（変更）してはいけません。

というのは禁止のニュアンスがうかがえるので、「指定（変更）する必要はありません」ぐらいの方が私は好みかな、と。

**Comment by hail2u** [comment]
どちらのHTML仕様からも「strong native semantics」という言葉がが消えているようなので、ARIA in HTMLで頻繁に使われる「implicit ARIA semantics」に統一しておきます。

> 禁止のニュアンス

仕様（ARIA in HTML）ではそのような感じ（冗長さの警告）だと思うのですが、ベスト・プラクティス的には禁止に寄せた方が良いんじゃないかな、ということでそうなっています。「指定しないようにしましょう」くらいにすると良さそうですかね？

**Comment by momdo** [comment]
> 「指定しないようにしましょう」くらいにすると良さそうですかね？

それでもいいと思います。（オススメしない、ぐらいの感じが一番いいのかなぁと。）
