### ISSUE TITLE
Discussion: Omitting `for` attribute in 'input' element isn't a good practice

### ISSUE THREAD

**Issue by jonathanlinat** [hail2u/html-best-practices#42]
As titled, [omitting `for` attribute in `input` element](https://github.com/hail2u/html-best-practices#omit-for-attribute-if-possible) **ISN'T** a good practice.

As [mentioned by MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form#The_%3Clabel%3E_element), you should use this attribute _because some assistive technologies do not understand implicit relationships between labels and widgets_.

**Comment by hail2u** [comment]
[This test][1] proves that wrapping `input` element with `label` element is safe. I write this practice based on this test.

Your quoted paragraph was written on 2012. It’s too old. If you find at least one assistive technology that does not support this markup, tell me here and re-open this issue. I’ll fix this practive. Thanks!

[1]: http://www.html5accessibility.com/tests/form-labels.html

**Comment by jonathanlinat** [comment]
Hey Kim :)

> Your quoted paragraph was written on 2012.

YOUR quoted test is old (2012) and use old versions of assistive technologies.
My quoted doc has been last updated on May 17, 2017.

Here proper docs about label and input and their association:
- https://www.w3.org/TR/WCAG20-TECHS/H44.html
- http://webaim.org/techniques/forms/controls

And the [most updated test](https://www.powermapper.com/tests/screen-readers/labelling/input-text-label-for/) you can find nowadays.

**Comment by hail2u** [comment]
Yes, test is old. However, there is no regression here (for now).

WCAG Note, WebAIM document, and the test you refer proves that `label` element with `for` attribute is OK, but does not proves that wrapping `input` element with `label` element is not OK.

Is there a platform that does not support this markup?
