### ISSUE TITLE
Discussion: What's the best way to contribute to this project?

### ISSUE THREAD

**Issue by jonathanlinat** [hail2u/html-best-practices#43]
Hey Kim,

I'd like to translate your documentation in French (native speaker) and Spanish (I live in South America).

But I have one issue here:
1. I can create a local branch, work on it, commit and push my changes into this same branch.
2. I cannot create a new Pull Request to require you to review my changes and merge them to your master branch.

So, what's the proper way to contribute to this project?

**EDIT**: Do I need to fork this repository as [explained here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)?

**Comment by hail2u** [comment]
Yes, you need to fork it.
