### ISSUE TITLE
「XML宣言を使用しない」について

### ISSUE THREAD

**Issue by satoshiiorg** [hail2u/html-best-practices#46]
はじめまして。「普通のHTMLの書き方」拝読しました。
ほとんどの知識がXHTML 1.1時代でとまっていたので、大変参考になりました。
気付いた点がいくつかあるのでコメントさせてください。

---

「XML宣言を使用しない」の節について、大筋は同意なのですが、そもそも現在HTML構文(text/html)ではXML宣言の記述はパースエラーになると思います。

https://html.spec.whatwg.org/multipage/parsing.html#tag-open-state
>12.2.5.6 Tag open state
>(中略)
>U+003F QUESTION MARK (`?`)
>This is an unexpected-question-mark-instead-of-tag-name parse error.

https://html.spec.whatwg.org/multipage/parsing.html#parse-error-unexpected-question-mark-instead-of-tag-name
>The common reason for this error is an XML processing instruction (e.g., `<?xml-stylesheet type="text/css" href="style.css"?>`) or an XML declaration (e.g., `<?xml version="1.0" encoding="UTF-8"?>`) being used in HTML.

逆に、XHTML構文(application/xhtml+xml, etc.)を使う場合はXML仕様に従う必要があるため、XML宣言はむしろ記述*すべき*です。

https://www.w3.org/TR/xml/#sec-prolog-dtd
> [Definition: XML documents should begin with an XML declaration which specifies the version of XML being used.] 

HTML仕様にも、文字コードの宣言に関連して以下の記述があります。

https://html.spec.whatwg.org/multipage/semantics.html#charset
> In XML, the XML declaration should be used for inline character encoding information, if necessary.

とは言え、おそらく九分九厘の人が使わないであろうXHTML構文についての説明は冗長かと思うので、単に「text/htmlではパースエラーになるので書いてはいけません」という説明の方が話が早いかと思いました。

**Comment by hail2u** [comment]
長い方は[別リポジトリー](https://github.com/hail2u/html-best-practices-ja-detailed)に移動しました。
