### ISSUE TITLE
「UTF-8を使う」について

### ISSUE THREAD

**Issue by satoshiiorg** [hail2u/html-best-practices#47]
こちらも大筋については同意なのですが、WHATWG HTMLではすでにUTF-8が必須化されているようですので、もはやUTF-8にすべきというよりもしなければならない、が適切かと思いました。

https://html.spec.whatwg.org/multipage/semantics.html#charset
>Regardless of whether a character encoding declaration is present or not, the actual character encoding used to encode the document must be UTF-8. [ENCODING]

**Comment by hail2u** [comment]
実はUTF-8であるべき、くらいにしておきたかったんですが、仕様をじっくり読むと、もうそんな場合じゃなさそうですね。まだ少し語調が弱めですが、

- `<meta-charset="utf-8">`としか書けないこと
- HTML文書はUTF-8でなければならないこと

を言及し、実利的な面からも……という形で「UTF-8で書きましょう」としました。これでどうでしょうか？
