### ISSUE TITLE
細かい表現の修正案

### ISSUE THREAD

**Issue by satoshiiorg** [hail2u/html-best-practices#48]
内容に直接関係ない話ですが。

「コメントではその内容の前後へ空白文字を置く」について。
>いくつかの文字はコメントの開始タグの直後や終了タグの直前に書けません。

多分今でもコメントの開始終了はタグ扱いはしないのではないかと思いました。
定義が変わっていたらごめんなさい。

「必要な時はimg要素へalt属性を追加する」について。
>仕様で明言されているように、alt属性は必ず指定すべきで、空であってはいけません。

この辺現在の仕様を知らず、後続の内容を読んで「省略してもいいの？だめなの？」と少し混乱したので、「基本的には必ず指定すべきで～」としてあると分かりやすいかと思いました。
いずれも瑣末な話ですが……。

**Comment by hail2u** [comment]
コメントの方は手癖でタグと書いてしまっていたようです。英語の方も含め、ズバッと削除しました。

画像の方は仕様の「Except where otherwise specified」を踏まえた感じに追加しました。
