### ISSUE TITLE
「CSSのtype属性は省略する」の最終行について

### ISSUE THREAD

**Issue by sakahukamaki** [hail2u/html-best-practices#49]
はじめまして。まだ読んでいる途中なのですが、文章の間違いを見つけたので報告します。

> その場合には適切なMIMEタイプを指定する必要があるのることは頭に入れておきましょう。

上記ですが、「必要があることは」かと思われます。本来ならPRを作成すべきところですが、簡単な報告ですませてしまい大変申し訳ないです。

貴重な知見の共有、ありがとうございます！

**Comment by hail2u** [comment]
前後もおかしかったので、まとめてなおしました👍
