### ISSUE TITLE
「内部リンクには絶対パスを使う」で絶対と相対が逆

### ISSUE THREAD

**Issue by crazymaster** [hail2u/html-best-practices#55]
「内部リンクには絶対パスを使う」のセクションで、タイトルもそうなのですが
絶対と相対が逆になっている箇所があります。

**Comment by hail2u** [comment]
- `https://`で始まる -> 絶対URL
- `//`で始まる -> 相対URL
- `/`で始まる -> 絶対パス
- `./`や`../`などその他文字で始まる -> 相対パス

という定義で書いています。何度か確認してみましたが、意図したとおりになっている（`/`で始まるパス、つまり絶対パスを使う）と思います。

**Comment by crazymaster** [comment]
すいません、絶対URLと絶対パスの定義をよく読まずに混同してました...
絶対パスをサイトルート相対パスと書く or 表現できることを書いた方が丁寧かなと思います。
