### ISSUE TITLE
add syntax highlight

### ISSUE THREAD

**Issue by gulping** [hail2u/html-best-practices#56]
[GitHub Flavored Markdown](https://github.github.com/gfm/#fenced-code-blocks)を含む多くのMarkdown仕様/レンダラが、
info string付きのFenced code blocksによるシンタックスハイライトに対応しています。

````
```html
<code class="language-html">&lt;!DOCTYPE html&gt;</code>
```
````

↓

```html
<code class="language-html">&lt;!DOCTYPE html&gt;</code>
```

----

属性や入れ子が多いコード例で目が滑ることがあったため、
シンタックスハイライトの補助があるとより読みやすくなると思いました。

**Comment by hail2u** [comment]
興味がありません。

**Comment by gulping** [comment]
close後に無遠慮ながら、他の方に需要がなくはないと思ったので
日本語版(`/README.ja.md`)のみシンタックスハイライトをつけたものを共有させていただきたいと思います。
https://github.com/gulping/html-best-practices/blob/master/README.ja.md#一般

ご検討いただきありがとうございました。
