### ISSUE TITLE
内部リンクには絶対パスを使う について

### ISSUE THREAD

**Issue by azpino12** [hail2u/html-best-practices#59]
https://hail2u.net/documents/html-best-practices.html
こちらのページに書いてあった、内容とても勉強になりました。

読んでて、少し気になったのですが、いい例と悪い例は逆ではないでしょうか？
以下引用
```
内部リンクには絶対パスを使う
絶対パスはインターネット回線のないローカルの環境でもうまく動きます。

悪い例:

<link rel="apple-touch-icon" href="http://you.example.com/apple-touch-icon-precomposed.png">
...
<p>You can find more at <a href="//you.example.com/contact.html">contact page</a>.</p>
良い例:

<link rel="apple-touch-icon" href="/apple-touch-icon-precomposed.png">
...
<p>You can find more at <a href="/contact.html">contact page</a>.</p>


```

GitHubの利用も初めてで、書く場所や内容が間違っていたらすみません。

**Comment by hail2u** [comment]
悪い例のURLは[絶対URL](https://url.spec.whatwg.org/#absolute-url-string)と[スキーム相対URL](https://url.spec.whatwg.org/#scheme-relative-url-string)と呼ばれています。良い例のようなスラッシュで始まるものが[絶対パス（または絶対パスURL）](https://url.spec.whatwg.org/#path-absolute-url-string)です。

内容についてでしたら、なぜ逆なのかをもうちょっと詳しくお願いします。

**Comment by azpino12** [comment]
申し訳ありません。
絶対URLと、絶対パスURLのことをよく理解していませんでした。

絶対URLを使うべきだと推奨しているのだと勘違いしておりました。
本当にすみません。

**Comment by hail2u** [comment]
いいえ、僕が間違っていることも良くあるので、フィードバックはありがたいです。
