### ISSUE TITLE
Why not <dl> for interview/dialogue?

### ISSUE THREAD

**Issue by utrenkner** [hail2u/html-best-practices#68]
I recently searched for how to best markup an interview. I was surprised that many people recommended ''dl'', which I had only come to know as definition list. But upon reading the [(living) HTML standard](https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element), I had to agree. It says that the ''dl'' element represents an association list consisting of zero or more name-value groups. And:

> Name-value groups may be [...] questions and answers

Therefore, your recommendation of not using ''dl'' for dialogues may be a bit too strict. At least for interview-like dialogues, ''dl'' looks like a good match.

**Comment by hail2u** [comment]
The dl element section have a note:

> The dl element is inappropriate for marking up dialogue. See some [examples of how to mark up dialogue][1].


[1]: https://html.spec.whatwg.org/multipage/semantics-other.html#conversations

**Comment by utrenkner** [comment]
You are right, I had not seen this. The funny thing is, that under the link you included, it says that there is no specific element that should be used for conversations. And the third example shows the use of ''dl'' for a specific conversation...

Therefore, I will continue with what I wrote before: In a clear question/answer setting (interview), I will use ''dl''. But I understand that in most other conversation this is not recommended.
