### ISSUE TITLE
Why should I not omit unnecessary closing tags?

### ISSUE THREAD

**Issue by nuxodin** [hail2u/html-best-practices#69]
It is absolutely allowed to leave out `</body> </html> </td> </option>` and so on.
And I find it even better and more legible.

**Comment by hail2u** [comment]
- [The rule of omitting tags][1] is very complex
- Some non-browser parser (such as angular-html-parser used in prettier) does not fully support 
- Most elements (95 of 115) are not omissible
- “Don’t omit closing tag” is *always* safe and works on everywhere


[1]: https://html.spec.whatwg.org/multipage/syntax.html#optional-tags

**Comment by nuxodin** [comment]
Ok, maybe it's safer if someone doesn't have a clue about it. but I wouldn't call it best practice.
