### ISSUE TITLE
Making the `h1` and `p` as the child of the anchor tag is not valid HTML

### ISSUE THREAD

**Issue by vanzasetia** [hail2u/html-best-practices#73]
The HTML code snippet inside the [Don’t split same link that can be grouped](https://github.com/hail2u/html-best-practices#dont-split-same-link-that-can-be-grouped) section, specifically the **Good** one, shows that wrapping the `h1` and `p` tag inside an anchor tag.
```html
<a href="https://whatwg.org/">
  <h1>WHATWG</h1>

  <p>A community maintaining and evolving HTML since 2004.</p>
</a>
```
It could be essentially an invalid HTML according to [Can I Include site](https://caninclude.glitch.me/).
- [Test `p` as the child of `a` tag](https://caninclude.glitch.me/caninclude?child=p&parent=a)
- [Test `h1` as the child of `a` tag](https://caninclude.glitch.me/caninclude?child=h1&parent=a)

**Comment by hail2u** [comment]
[`a` element][1] content model is:

> Transparent, but there must be no interactive content descendant, a element descendant, or descendant with the tabindex attribute specified.

`<a><p>text <a>link</a> text</p></a>` is invalid, but `<a><p>text text text</p></a>` is valid. 

[1]: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element
